services:
  web:
    build:
      context: .
    container_name: plumber-django-dev
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    environment:
      DJANGO_DEBUG: "1"
      DJANGO_ALLOWED_HOSTS: "127.0.0.1,localhost,testserver"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped
