# Generated by Django 5.2.16 on 2026-07-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_seed_project_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=60)),
                ('message', models.TextField(blank=True)),
                ('request_type', models.CharField(choices=[('standard', 'Standard Request'), ('urgent', 'Urgent Request'), ('commercial', 'Commercial B2B Clients'), ('complex', 'High Complexity Request'), ('general', 'General Request')], default='general', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
