# Generated by Django 5.2.16 on 2026-09-14 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_requestsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=120, unique=True)),
                ('label', models.CharField(max_length=160)),
                ('image', models.FileField(blank=True, upload_to='site/')),
                ('default_path', models.CharField(blank=True, max_length=255)),
                ('alt_text', models.CharField(blank=True, max_length=160)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('label',),
            },
        ),
        migrations.CreateModel(
            name='SiteText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=120, unique=True)),
                ('label', models.CharField(max_length=160)),
                ('text', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('label',),
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.FileField(blank=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.FileField(blank=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(default='#5A3E2B', help_text='Main site color in HEX format.', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a color in HEX format, for example #5A3E2B.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Spasibo LLC', max_length=120),
        ),
    ]
