# Generated by Django 5.2.16 on 2026-09-14 13:10

from django.db import migrations


SITE_TEXTS = [
    ("meta_title", "Meta title", "Spasibo - Painting, Flooring and Custom Project Services"),
    ("header_address_label", "Header address label", "Address"),
    ("header_phone_label", "Header phone label", "Call us"),
    ("header_email_label", "Header email label", "Send Us Email"),
    ("nav_home", "Navigation: Home", "Home"),
    ("nav_services", "Navigation: Services", "Services"),
    ("nav_projects", "Navigation: Projects", "Projects"),
    ("nav_contact", "Navigation: Contact", "Contact"),
    ("hero_subtitle", "Hero subtitle", "Trusted Home Improvement Team"),
    ("hero_intro_title", "Hero intro title", "Refresh Your Space With Skilled Finish Work"),
    (
        "hero_intro_text",
        "Hero intro text",
        "We handle painting, flooring, deck, trim, wall restoration, and custom repair projects with clean planning, professional tools, and careful execution.",
    ),
    ("hero_phone_label", "Hero phone label", "Call us"),
    ("button_leave_request", "Button: leave request", "Leave a Request"),
    ("services_subtitle", "Services subtitle", "Painting, Flooring & Finish Work"),
    ("services_title_line_1", "Services title line 1", "Quality & Reliability"),
    ("services_title_line_2", "Services title line 2", "With 100% Satisfaction"),
    (
        "services_intro",
        "Services intro",
        "From detailed painting to flooring, decks, and custom repair work, our team handles practical projects with clean planning, reliable tools, and careful finishing.",
    ),
    ("service_painting_title", "Service card: painting title", "Painting Projects"),
    (
        "service_painting_text",
        "Service card: painting text",
        "Interior and exterior painting for homes, garages, fences, basements, concrete, and asphalt. We handle high-reach projects, wall damage restoration, color selection, and professional application with sprayers, rollers, brushes, extensions, ladders, and scaffolding.",
    ),
    ("service_flooring_title", "Service card: flooring title", "Flooring and Deck"),
    (
        "service_flooring_text",
        "Service card: flooring text",
        "Installation of laminate, hardwood, engineered wood, decks, trim, baseboards, and stairs. We can deliver materials to the site, remove old flooring, and haul away demolition waste so the project stays organized from start to finish.",
    ),
    ("service_custom_title", "Service card: custom title", "Custom Projects"),
    (
        "service_custom_text",
        "Service card: custom text",
        "Our professional team is ready to review creative, unusual, or more complex projects. If your job needs flexible planning, careful problem solving, and hands-on experience, we can help define the scope and deliver the work.",
    ),
    ("projects_subtitle", "Projects subtitle", "Painting, Flooring & Finish Work"),
    ("projects_title", "Projects title", "Recent Home Improvement Projects"),
    (
        "projects_intro",
        "Projects intro",
        "Explore examples of practical painting, flooring, deck, and repair work completed with careful preparation, clean execution, and durable finishing.",
    ),
    ("projects_filter_all", "Projects filter: all", "All"),
    ("projects_empty_message", "Projects empty message", "No active projects yet. Add project cases in the admin panel."),
    ("free_estimates_title", "Free estimates title", "Free Estimates"),
    (
        "free_estimates_text",
        "Free estimates text",
        "Tell us about your painting, flooring, deck, or repair project and we will help you plan the next step.",
    ),
    ("company_title", "Company title", "Spasibo LLC"),
    (
        "company_paragraph_1",
        "Company paragraph 1",
        "Our team has more than 15 years of experience in construction and finish work. We understand how building materials, surface preparation, flooring systems, coatings, trims, and protective finishes behave over time, and we use that knowledge to create projects that are done once and built to last.",
    ),
    (
        "company_paragraph_2",
        "Company paragraph 2",
        "We help clients choose practical materials, plan the right sequence of work, avoid rushed fixes, and finish each detail with clean execution. Whether it is painting, flooring, deck work, wall restoration, or a custom project, our goal is a durable result that looks good and serves your space for years.",
    ),
    ("request_title_line_1", "Request title line 1", "Tell Us What Kind Of"),
    ("request_title_line_2", "Request title line 2", "Project You Need"),
    ("request_option_standard", "Request option: standard", "Standard Request"),
    ("request_option_urgent", "Request option: urgent", "Urgent Request"),
    ("request_option_commercial", "Request option: commercial", "B2B Clients"),
    ("request_option_complex", "Request option: complex", "Complex Request"),
    ("footer_copyright_prefix", "Footer copyright prefix", "Copyright"),
    ("footer_copyright_suffix", "Footer copyright suffix", "All rights reserved."),
    ("footer_privacy_label", "Footer privacy label", "Privacy Policy"),
    ("footer_cookie_label", "Footer cookie label", "Cookie Policy"),
    ("footer_terms_label", "Footer terms label", "Terms of Service"),
    ("request_modal_title", "Request modal title", "Request a Quote"),
    ("form_name_placeholder", "Form name placeholder", "Name"),
    ("form_phone_placeholder", "Form phone placeholder", "Phone"),
    ("form_message_placeholder", "Form message placeholder", "Tell us a little about the project"),
    ("form_submit_button", "Form submit button", "Submit Request"),
    ("legal_back_home", "Legal pages: back link", "Back to Home"),
]


SITE_IMAGES = [
    (
        "hero_background",
        "Hero background image",
        "/static/plumber/assets/images/main-slider/hero.jpg",
        "Exterior home improvement project",
    ),
    (
        "service_painting",
        "Service image: painting",
        "/static/plumber/assets/images/resource/painting.jpg",
        "Painting project",
    ),
    (
        "service_flooring",
        "Service image: flooring and deck",
        "/static/plumber/assets/images/resource/flooring.jpg",
        "Flooring and deck project",
    ),
    (
        "service_custom",
        "Service image: custom project",
        "/static/plumber/assets/images/resource/custom.jpg",
        "Custom project",
    ),
]


LEGAL_PAGES = [
    (
        "privacy-policy",
        "Privacy Policy",
        """Last updated: July 14, 2026

Spasibo LLC respects your privacy. This policy explains what information we collect when you contact us through the website and how we use it.

We may collect your name, phone number, email address, project details, and technical information needed to operate the website. We use this information to respond to your requests, provide estimates, improve our service, and maintain site security.

We do not sell your personal information. We may share information only with service providers who help us operate the website or when required by law.

To request access, correction, or deletion of your information, contact us using the phone or email listed on the website.""",
    ),
    (
        "cookie-policy",
        "Cookie Policy",
        """Last updated: July 14, 2026

This Cookie Policy explains how Spasibo LLC may use cookies and similar technologies on this website.

Cookies can help the website function, remember basic preferences, measure performance, and improve user experience. You can control cookies through your browser settings.

If analytics, advertising, or third-party tools are added in the future, this page should be updated to describe those tools and their cookie usage.""",
    ),
    (
        "terms-of-service",
        "Terms of Service",
        """Last updated: July 14, 2026

By using this website, you agree to these Terms of Service. The website provides general information about Spasibo LLC services and a way to submit project requests.

Submitting a request does not create a contract or guarantee service availability. Project scope, pricing, timing, and materials are confirmed separately in direct communication with Spasibo LLC.

Website content is provided for general informational purposes. Spasibo LLC may update the website, services, or these terms at any time.""",
    ),
]


def seed_content(apps, schema_editor):
    SiteSettings = apps.get_model("pages", "SiteSettings")
    SiteText = apps.get_model("pages", "SiteText")
    SiteImage = apps.get_model("pages", "SiteImage")
    LegalPage = apps.get_model("pages", "LegalPage")

    settings, _ = SiteSettings.objects.get_or_create(pk=1)
    settings.site_name = settings.site_name or "Spasibo LLC"
    settings.primary_color = "#5A3E2B"
    settings.save(update_fields=["site_name", "primary_color"])

    for key, label, text in SITE_TEXTS:
        SiteText.objects.update_or_create(
            key=key,
            defaults={"label": label, "text": text},
        )

    for key, label, default_path, alt_text in SITE_IMAGES:
        SiteImage.objects.update_or_create(
            key=key,
            defaults={"label": label, "default_path": default_path, "alt_text": alt_text},
        )

    for slug, title, content in LEGAL_PAGES:
        LegalPage.objects.update_or_create(
            slug=slug,
            defaults={"title": title, "content": content},
        )


def unseed_content(apps, schema_editor):
    SiteText = apps.get_model("pages", "SiteText")
    SiteImage = apps.get_model("pages", "SiteImage")
    LegalPage = apps.get_model("pages", "LegalPage")

    SiteText.objects.filter(key__in=[key for key, _, _ in SITE_TEXTS]).delete()
    SiteImage.objects.filter(key__in=[key for key, _, _, _ in SITE_IMAGES]).delete()
    LegalPage.objects.filter(slug__in=[slug for slug, _, _ in LEGAL_PAGES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_legalpage_siteimage_sitetext_sitesettings_favicon_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_content, unseed_content),
    ]
